export const AuditAction = {
  ADMIN_LOGIN: "ADMIN_LOGIN",

  CREATE_ELECTION: "CREATE_ELECTION",
  UPDATE_ELECTION: "UPDATE_ELECTION",
  DELETE_ELECTION: "DELETE_ELECTION",
  ACTIVATE_ELECTION: "ACTIVATE_ELECTION",
  CLOSE_ELECTION: "CLOSE_ELECTION",
  ARCHIVE_ELECTION: "ARCHIVE_ELECTION",
  PUBLISH_RESULTS: "PUBLISH_RESULTS",
  HIDE_RESULTS: "HIDE_RESULTS",

  CREATE_CANDIDATE: "CREATE_CANDIDATE",
  UPDATE_CANDIDATE: "UPDATE_CANDIDATE",
  DELETE_CANDIDATE: "DELETE_CANDIDATE",
  TOGGLE_CANDIDATE: "TOGGLE_CANDIDATE",

  GENERATE_TOKENS: "GENERATE_TOKENS",
  INVALIDATE_TOKEN: "INVALIDATE_TOKEN"
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
