export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  ORIGIN_MISSING: "ORIGIN_MISSING",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",

  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_USED: "TOKEN_USED",
  TOKEN_AMBIGUOUS: "TOKEN_AMBIGUOUS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ELECTION_INACTIVE: "ELECTION_INACTIVE",
  CANDIDATE_INVALID: "CANDIDATE_INVALID"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
